Feature to activate and deactive the sensor
neobotix/neo_usboard_v2-2 pull request #2
Opened 2023-03-17 09:46 UTC by padhupradheep

Firmware is updated and the necessary changes are also adapted to the ROS node. Now the user would be able to activate and deactivate their ultrasonic sensor depending on their needs.

2023-03-17 10:43 UTC, neojaw approved these changes

2023-03-17 10:43 UTC, neojaw commented on src/neo_usboard_v2_node.cpp
> +		config=NULL;
Since this is a `std::shared_ptr` I would prefer `nullptr` instead of `NULL`.

2023-03-17 12:07 UTC, neojaw requested changes

2023-03-17 12:07 UTC, neojaw commented on src/neo_usboard_v2_node.cpp
> +		request_config();
Actually we don't need that since it will be requested after one second anyway.

2023-03-17 12:34 UTC, neojaw approved these changes

2023-03-20 10:43 UTC, padhupradheep commented
tests done! Merging!

2023-03-20 10:44 UTC, merged